### ISSUE TITLE
README.md example role causing error

### ISSUE THREAD

**Issue by hilliao** [ichundu/ansible-role-squid#4]
The following example playbook failed with error: role squid not found. Since the project name is ansible-role-squid, the directory for the role is most likely ansible-role-squid. 

```
- hosts: servers
  roles:
    - role: squid
      squid_http_ports:
        - 3128
        - 80
```
Should be changed to 
```
- hosts: servers
  roles:
    - role: ansible-role-squid
      squid_http_ports:
        - 3128
        - 80
```
